var mb = {
    Buidings:[
      {
         "BuildingID":1,
         "BuildingType":1,
         "BuildingName":"林场",
         "BuildingDesc":"等级越高的林场每小时提供的木材越多",
         "BuildingDesc1":"林场是获得木材的场所，是建造建筑的重要资源。等级越高的林场每小时提供的木材越多。"
      },
      {
         "BuildingID":2,
         "BuildingType":1,
         "BuildingName":"农田",
         "BuildingDesc":"等级越高的农田每小时提供的粮食越多",
         "BuildingDesc1":"农田是出产粮食的场所，对战争有举足轻重的作用。等级越高的农田每小时提供的粮食越多。"
      },
      {
         "BuildingID":3,
         "BuildingType":1,
         "BuildingName":"石料场",
         "BuildingDesc":"等级越高的石料场每小时提供的石料越多",
         "BuildingDesc1":"石料场是获得石料的场所，是征兵、城防的重要资源。等级越高每小时提供的石料越多。"
      },
      {
         "BuildingID":4,
         "BuildingType":1,
         "BuildingName":"矿山",
         "BuildingDesc":"等级越高的矿山每小时提供的铁矿越多",
         "BuildingDesc1":"矿山是出产铁矿的场所，是研究科技的重要资源。等级越高的矿山每小时提供的铁矿越多。"
      },
      {
         "BuildingID":5,
         "BuildingType":1,
         "BuildingName":"秘库",
         "BuildingDesc":"等级越高可以保护更多资源免遭掠夺",
         "BuildingDesc1":"受到进攻时，秘库可以保护一定量的资源不被掠夺。等级越高可以保护更多的资源免遭掠夺。"
      },
      {
         "BuildingID":6,
         "BuildingType":1,
         "BuildingName":"仓库",
         "BuildingDesc":"等级越高可存放资源的量越大",
         "BuildingDesc1":"仓库内可以存放各种资源。等级越高可存放资源的量越大。"
      },
      {
         "BuildingID":7,
         "BuildingType":1,
         "BuildingName":"官府",
         "BuildingDesc":"等级越高的官府提高建造速度越快",
         "BuildingDesc1":"升级官府可以提高建筑的建造、升级速度，等级越高的官府提高建造速度越快。"
      },
      {
         "BuildingID":8,
         "BuildingType":1,
         "BuildingName":"军营",
         "BuildingDesc":"等级越高可以招募的兵种越多，速度越快",
         "BuildingDesc1":"军营是招募军队的场所。军营等级越高可以招募的兵种越高，而且征兵速度越快。"
      },
      {
         "BuildingID":9,
         "BuildingType":1,
         "BuildingName":"城防处",
         "BuildingDesc":"等级越高可以建造的城防越多，速度越快",
         "BuildingDesc1":"城防处是建造城防设施的场所。城防处等级越高可以建造的城防越高，且建造速度越快。"
      },
      {
         "BuildingID":10,
         "BuildingType":1,
         "BuildingName":"太学院",
         "BuildingDesc":"等级越高能够研究的科技越多，速度越快",
         "BuildingDesc1":"太学院是研究各种科技的场所。太学院等级越高能够研究的科技越多，且研究速度更快。"
      },
      {
         "BuildingID":11,
         "BuildingType":1,
         "BuildingName":"冶炼坊",
         "BuildingDesc":"等级越高的冶炼坊提升铁矿产量越高",
         "BuildingDesc1":"冶炼坊是提高铁矿产量的高级建造物。等级越高的冶炼坊提升铁矿产量越高。"
      },
      {
         "BuildingID":12,
         "BuildingType":1,
         "BuildingName":"磨坊",
         "BuildingDesc":"等级越高的磨坊提升粮食产量越高",
         "BuildingDesc1":"磨坊是提高粮食产量的高级建造物。等级越高的磨坊提升粮食产量越高。"
      },
      {
         "BuildingID":13,
         "BuildingType":1,
         "BuildingName":"馆驿",
         "BuildingDesc":"是加入并创建家族、联防的必须建筑物",
         "BuildingDesc1":"馆驿是接待外来使节的场所。建立馆驿后可以加入并创建家族、联防。"
      },
      {
         "BuildingID":14,
         "BuildingType":1,
         "BuildingName":"工部",
         "BuildingDesc":"等级越高则建筑、征兵、城防的速度越快",
         "BuildingDesc1":"工部是快速规划城池建设的顶级建筑。等级越高则建筑、征兵、城防的建造生产速度越快。"
      },
      {
         "BuildingID":15,
         "BuildingType":1,
         "BuildingName":"民居",
         "BuildingDesc":"等级越高提供的总人口越多",
         "BuildingDesc1":"民居是容纳建造人口的住所，建造建筑需要消耗人口。民居等级越高提供的总人口越多。"
      },
      {
         "BuildingID":16,
         "BuildingType":1,
         "BuildingName":"石料坊",
         "BuildingDesc":"等级越高的石料坊提升石料产量越高",
         "BuildingDesc1":"石料坊是提高石料产量的高级建造物。等级越高的石料坊提升石料产量越高。"
      },
      {
         "BuildingID":17,
         "BuildingType":1,
         "BuildingName":"木料坊",
         "BuildingDesc":"等级越高的木料坊提升木材产量越高",
         "BuildingDesc1":"木料坊是提高木材产量的高级建造物。等级越高的木料坊提升木材产量越高。"
      },
      {
         "BuildingID":18,
         "BuildingType":1,
         "BuildingName":"工匠铺",
         "BuildingDesc":"等级越高则每次战争后可修复城防数越多",
         "BuildingDesc1":"工匠铺可以修复战争中损坏的城防设施，等级越高则每次战争后可以修复的城防数越多。"
      },
      {
         "BuildingID":19,
         "BuildingType":1,
         "BuildingName":"拓荒营",
         "BuildingDesc":"等级越高则可开拓分城的数量越多",
         "BuildingDesc1":"拓荒营是建造分城的必须条件。拓荒营等级越高则可开拓分城的数量越多。"
      },
      {
         "BuildingID":33,
         "BuildingType":2,
         "BuildingName":"刺探",
         "BuildingDesc":"提升刺探他城成功率",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":34,
         "BuildingType":2,
         "BuildingName":"统率",
         "BuildingDesc":"提升可以同时操作的部队数量",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":35,
         "BuildingType":2,
         "BuildingName":"护甲",
         "BuildingDesc":"提升部队的防御力",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":36,
         "BuildingType":2,
         "BuildingName":"利刃",
         "BuildingDesc":"提升部队的近程攻击力",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":37,
         "BuildingType":2,
         "BuildingName":"神箭",
         "BuildingDesc":"提升部队的远程攻击力",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":38,
         "BuildingType":2,
         "BuildingName":"运送",
         "BuildingDesc":"提升运输兵种的移动速度",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":39,
         "BuildingType":2,
         "BuildingName":"负载",
         "BuildingDesc":"提升运输兵种的运输资源数量",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":40,
         "BuildingType":2,
         "BuildingName":"疾步",
         "BuildingDesc":"提升步兵兵种的移动速度",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":41,
         "BuildingType":2,
         "BuildingName":"狂奔",
         "BuildingDesc":"提升骑兵兵种的移动速度",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":42,
         "BuildingType":2,
         "BuildingName":"筑城",
         "BuildingDesc":"提升城防的防御力",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":43,
         "BuildingType":2,
         "BuildingName":"智慧",
         "BuildingDesc":"大幅提升科技研究速度",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":44,
         "BuildingType":2,
         "BuildingName":"神目",
         "BuildingDesc":"提升获知进攻方部队详情的概率",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":65,
         "BuildingType":3,
         "BuildingName":"陷阱",
         "BuildingDesc":"近程防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":66,
         "BuildingType":3,
         "BuildingName":"高级陷阱",
         "BuildingDesc":"近程防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":67,
         "BuildingType":3,
         "BuildingName":"箭塔",
         "BuildingDesc":"远程防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":68,
         "BuildingType":3,
         "BuildingName":"高级箭塔",
         "BuildingDesc":"远程防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":69,
         "BuildingType":3,
         "BuildingName":"滚石",
         "BuildingDesc":"中级防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":70,
         "BuildingType":3,
         "BuildingName":"擂木",
         "BuildingDesc":"高级防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":71,
         "BuildingType":3,
         "BuildingName":"火箱",
         "BuildingDesc":"高级防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":72,
         "BuildingType":3,
         "BuildingName":"绞车",
         "BuildingDesc":"顶级防御设施",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":97,
         "BuildingType":4,
         "BuildingName":"粮草兵",
         "BuildingDesc":"低级运输兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":98,
         "BuildingType":4,
         "BuildingName":"运输车",
         "BuildingDesc":"高级运输兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":99,
         "BuildingType":4,
         "BuildingName":"侦察兵",
         "BuildingDesc":"刺探专用兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":100,
         "BuildingType":4,
         "BuildingName":"拓荒部队",
         "BuildingDesc":"拓荒专用兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":101,
         "BuildingType":4,
         "BuildingName":"枪盾兵",
         "BuildingDesc":"近程防御兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":102,
         "BuildingType":4,
         "BuildingName":"强弩兵",
         "BuildingDesc":"远程防御兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":103,
         "BuildingType":4,
         "BuildingName":"重甲将军",
         "BuildingDesc":"同时拥有近远程防御的顶级兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":104,
         "BuildingType":4,
         "BuildingName":"长枪兵",
         "BuildingDesc":"低级近程攻击兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":105,
         "BuildingType":4,
         "BuildingName":"骑枪战将",
         "BuildingDesc":"高级近程攻击兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":106,
         "BuildingType":4,
         "BuildingName":"弓箭兵",
         "BuildingDesc":"低级远程攻击兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":107,
         "BuildingType":4,
         "BuildingName":"骑射战将",
         "BuildingDesc":"高级远程攻击兵种",
         "BuildingDesc1":"无"
      },
      {
         "BuildingID":129,
         "BuildingType":4,
         "BuildingName":"野猪",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":130,
         "BuildingType":4,
         "BuildingName":"豺狼",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":131,
         "BuildingType":4,
         "BuildingName":"老虎",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":132,
         "BuildingType":4,
         "BuildingName":"熊",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":133,
         "BuildingType":4,
         "BuildingName":"流氓",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":134,
         "BuildingType":4,
         "BuildingName":"马贼",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":135,
         "BuildingType":4,
         "BuildingName":"土匪",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":136,
         "BuildingType":4,
         "BuildingName":"山贼",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      },
      {
         "BuildingID":137,
         "BuildingType":4,
         "BuildingName":"山贼头目",
         "BuildingDesc":"",
         "BuildingDesc1":" "
      }
    ]
}
