var mbu = {
    UserRank:[
      {
         "RankType":1,
         "RankNumber":0,
         "NeedPoint":"0",
         "NextRank":"1",
         "usAttrValue":"20",
         "UserTitle":"烽火新手"
      }
 , 
      {
         "RankType":1,
         "RankNumber":1,
         "NeedPoint":"50",
         "NextRank":"2",
         "usAttrValue":"23",
         "UserTitle":"公士"
      }
 , 
      {
         "RankType":1,
         "RankNumber":2,
         "NeedPoint":"100",
         "NextRank":"3",
         "usAttrValue":"26",
         "UserTitle":"上造"
      }
 , 
      {
         "RankType":1,
         "RankNumber":3,
         "NeedPoint":"200",
         "NextRank":"4",
         "usAttrValue":"30",
         "UserTitle":"簪袅"
      }
 , 
      {
         "RankType":1,
         "RankNumber":4,
         "NeedPoint":"500",
         "NextRank":"5",
         "usAttrValue":"35",
         "UserTitle":"不更"
      }
 , 
      {
         "RankType":1,
         "RankNumber":5,
         "NeedPoint":"1000",
         "NextRank":"6",
         "usAttrValue":"40",
         "UserTitle":"大夫"
      }
 , 
      {
         "RankType":1,
         "RankNumber":6,
         "NeedPoint":"2000",
         "NextRank":"7",
         "usAttrValue":"46",
         "UserTitle":"官大夫"
      }
 , 
      {
         "RankType":1,
         "RankNumber":7,
         "NeedPoint":"5000",
         "NextRank":"8",
         "usAttrValue":"53",
         "UserTitle":"公大夫"
      }
 , 
      {
         "RankType":1,
         "RankNumber":8,
         "NeedPoint":"10000",
         "NextRank":"9",
         "usAttrValue":"61",
         "UserTitle":"公乘"
      }
 , 
      {
         "RankType":1,
         "RankNumber":9,
         "NeedPoint":"20000",
         "NextRank":"10",
         "usAttrValue":"70",
         "UserTitle":"五大夫"
      }
 , 
      {
         "RankType":1,
         "RankNumber":10,
         "NeedPoint":"30000",
         "NextRank":"11",
         "usAttrValue":"81",
         "UserTitle":"左庶长"
      }
 , 
      {
         "RankType":1,
         "RankNumber":11,
         "NeedPoint":"40000",
         "NextRank":"12",
         "usAttrValue":"93",
         "UserTitle":"右庶长"
      }
 , 
      {
         "RankType":1,
         "RankNumber":12,
         "NeedPoint":"50000",
         "NextRank":"13",
         "usAttrValue":"110",
         "UserTitle":"左更"
      }
 , 
      {
         "RankType":1,
         "RankNumber":13,
         "NeedPoint":"60000",
         "NextRank":"14",
         "usAttrValue":"120",
         "UserTitle":"中更"
      }
 , 
      {
         "RankType":1,
         "RankNumber":14,
         "NeedPoint":"80000",
         "NextRank":"15",
         "usAttrValue":"140",
         "UserTitle":"右更"
      }
 , 
      {
         "RankType":1,
         "RankNumber":15,
         "NeedPoint":"100000",
         "NextRank":"16",
         "usAttrValue":"160",
         "UserTitle":"少上造"
      }
 , 
      {
         "RankType":1,
         "RankNumber":16,
         "NeedPoint":"120000",
         "NextRank":"17",
         "usAttrValue":"180",
         "UserTitle":"大良造"
      }
 , 
      {
         "RankType":1,
         "RankNumber":17,
         "NeedPoint":"140000",
         "NextRank":"18",
         "usAttrValue":"210",
         "UserTitle":"驷车庶长"
      }
 , 
      {
         "RankType":1,
         "RankNumber":18,
         "NeedPoint":"160000",
         "NextRank":"19",
         "usAttrValue":"240",
         "UserTitle":"大庶长"
      }
 , 
      {
         "RankType":1,
         "RankNumber":19,
         "NeedPoint":"180000",
         "NextRank":"20",
         "usAttrValue":"280",
         "UserTitle":"关内侯"
      }
 , 
      {
         "RankType":1,
         "RankNumber":20,
         "NeedPoint":"200000",
         "NextRank":"0",
         "usAttrValue":"320",
         "UserTitle":"彻侯"
      }
 , 
      {
         "RankType":2,
         "RankNumber":0,
         "NeedPoint":"0",
         "NextRank":"1",
         "usAttrValue":"0",
         "UserTitle":"卒夫"
      }
 , 
      {
         "RankType":2,
         "RankNumber":1,
         "NeedPoint":"20",
         "NextRank":"2",
         "usAttrValue":"30",
         "UserTitle":"伍夫长"
      }
 , 
      {
         "RankType":2,
         "RankNumber":2,
         "NeedPoint":"50",
         "NextRank":"3",
         "usAttrValue":"50",
         "UserTitle":"十夫长"
      }
 , 
      {
         "RankType":2,
         "RankNumber":3,
         "NeedPoint":"120",
         "NextRank":"4",
         "usAttrValue":"80",
         "UserTitle":"百夫长"
      }
 , 
      {
         "RankType":2,
         "RankNumber":4,
         "NeedPoint":"200",
         "NextRank":"5",
         "usAttrValue":"120",
         "UserTitle":"千夫长"
      }
 , 
      {
         "RankType":2,
         "RankNumber":5,
         "NeedPoint":"400",
         "NextRank":"6",
         "usAttrValue":"170",
         "UserTitle":"护军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":6,
         "NeedPoint":"700",
         "NextRank":"7",
         "usAttrValue":"230",
         "UserTitle":"监军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":7,
         "NeedPoint":"1000",
         "NextRank":"8",
         "usAttrValue":"300",
         "UserTitle":"裨将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":8,
         "NeedPoint":"1500",
         "NextRank":"9",
         "usAttrValue":"380",
         "UserTitle":"偏将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":9,
         "NeedPoint":"2500",
         "NextRank":"10",
         "usAttrValue":"470",
         "UserTitle":"校尉"
      }
 , 
      {
         "RankType":2,
         "RankNumber":10,
         "NeedPoint":"4000",
         "NextRank":"11",
         "usAttrValue":"570",
         "UserTitle":"中郎将"
      }
 , 
      {
         "RankType":2,
         "RankNumber":11,
         "NeedPoint":"6000",
         "NextRank":"12",
         "usAttrValue":"680",
         "UserTitle":"护军将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":12,
         "NeedPoint":"10000",
         "NextRank":"13",
         "usAttrValue":"800",
         "UserTitle":"领军将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":13,
         "NeedPoint":"14000",
         "NextRank":"14",
         "usAttrValue":"930",
         "UserTitle":"征北将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":14,
         "NeedPoint":"20000",
         "NextRank":"15",
         "usAttrValue":"1070",
         "UserTitle":"征西将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":15,
         "NeedPoint":"28000",
         "NextRank":"16",
         "usAttrValue":"1220",
         "UserTitle":"征南将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":16,
         "NeedPoint":"38000",
         "NextRank":"17",
         "usAttrValue":"1380",
         "UserTitle":"征东将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":17,
         "NeedPoint":"50000",
         "NextRank":"18",
         "usAttrValue":"1550",
         "UserTitle":"卫将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":18,
         "NeedPoint":"62000",
         "NextRank":"19",
         "usAttrValue":"1730",
         "UserTitle":"车骑将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":19,
         "NeedPoint":"76000",
         "NextRank":"20",
         "usAttrValue":"1920",
         "UserTitle":"骠骑将军"
      }
 , 
      {
         "RankType":2,
         "RankNumber":20,
         "NeedPoint":"92000",
         "NextRank":"0",
         "usAttrValue":"2120",
         "UserTitle":"上将军"
      }
 , 
      {
         "RankType":3,
         "RankNumber":0,
         "NeedPoint":"0",
         "NextRank":"1",
         "usAttrValue":"0",
         "UserTitle":"白丁"
      }
 , 
      {
         "RankType":3,
         "RankNumber":1,
         "NeedPoint":"40",
         "NextRank":"2",
         "usAttrValue":"40",
         "UserTitle":"里长"
      }
 , 
      {
         "RankType":3,
         "RankNumber":2,
         "NeedPoint":"80",
         "NextRank":"3",
         "usAttrValue":"80",
         "UserTitle":"亭长"
      }
 , 
      {
         "RankType":3,
         "RankNumber":3,
         "NeedPoint":"200",
         "NextRank":"4",
         "usAttrValue":"130",
         "UserTitle":"乡长"
      }
 , 
      {
         "RankType":3,
         "RankNumber":4,
         "NeedPoint":"300",
         "NextRank":"5",
         "usAttrValue":"190",
         "UserTitle":"县司空"
      }
 , 
      {
         "RankType":3,
         "RankNumber":5,
         "NeedPoint":"500",
         "NextRank":"6",
         "usAttrValue":"260",
         "UserTitle":"县司马"
      }
 , 
      {
         "RankType":3,
         "RankNumber":6,
         "NeedPoint":"700",
         "NextRank":"7",
         "usAttrValue":"340",
         "UserTitle":"县尉"
      }
 , 
      {
         "RankType":3,
         "RankNumber":7,
         "NeedPoint":"1000",
         "NextRank":"8",
         "usAttrValue":"430",
         "UserTitle":"县丞"
      }
 , 
      {
         "RankType":3,
         "RankNumber":8,
         "NeedPoint":"1200",
         "NextRank":"9",
         "usAttrValue":"530",
         "UserTitle":"县令"
      }
 , 
      {
         "RankType":3,
         "RankNumber":9,
         "NeedPoint":"1600",
         "NextRank":"10",
         "usAttrValue":"640",
         "UserTitle":"监御史"
      }
 , 
      {
         "RankType":3,
         "RankNumber":10,
         "NeedPoint":"2400",
         "NextRank":"11",
         "usAttrValue":"760",
         "UserTitle":"郡都尉"
      }
 , 
      {
         "RankType":3,
         "RankNumber":11,
         "NeedPoint":"3600",
         "NextRank":"12",
         "usAttrValue":"890",
         "UserTitle":"郡太守"
      }
 , 
      {
         "RankType":3,
         "RankNumber":12,
         "NeedPoint":"5200",
         "NextRank":"13",
         "usAttrValue":"1030",
         "UserTitle":"大司士"
      }
 , 
      {
         "RankType":3,
         "RankNumber":13,
         "NeedPoint":"7200",
         "NextRank":"14",
         "usAttrValue":"1180",
         "UserTitle":"大司寇"
      }
 , 
      {
         "RankType":3,
         "RankNumber":14,
         "NeedPoint":"9600",
         "NextRank":"15",
         "usAttrValue":"1340",
         "UserTitle":"大司空"
      }
 , 
      {
         "RankType":3,
         "RankNumber":15,
         "NeedPoint":"13000",
         "NextRank":"16",
         "usAttrValue":"1510",
         "UserTitle":"大司徒"
      }
 , 
      {
         "RankType":3,
         "RankNumber":16,
         "NeedPoint":"16000",
         "NextRank":"17",
         "usAttrValue":"1690",
         "UserTitle":"大司马"
      }
 , 
      {
         "RankType":3,
         "RankNumber":17,
         "NeedPoint":"20000",
         "NextRank":"18",
         "usAttrValue":"1880",
         "UserTitle":"太保"
      }
 , 
      {
         "RankType":3,
         "RankNumber":18,
         "NeedPoint":"24000",
         "NextRank":"19",
         "usAttrValue":"2080",
         "UserTitle":"太傅"
      }
 , 
      {
         "RankType":3,
         "RankNumber":19,
         "NeedPoint":"32000",
         "NextRank":"20",
         "usAttrValue":"2290",
         "UserTitle":"太师"
      }
 , 
      {
         "RankType":3,
         "RankNumber":20,
         "NeedPoint":"44000",
         "NextRank":"0",
         "usAttrValue":"2510",
         "UserTitle":"丞相"
      }
    ]
}
